"""empty message

Revision ID: edad4bf5c712
Revises: 1f8aafded866
Create Date: 2024-04-07 12:56:23.239459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edad4bf5c712'
down_revision: Union[str, None] = '1f8aafded866'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('sido', sa.Integer(), nullable=False))
    op.add_column('city', sa.Column('gugun', sa.Text(), nullable=False))
    op.drop_column('city', 'level')
    op.drop_column('city', 'area_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('city', sa.Column('area_name', sa.TEXT(), nullable=False))
    op.add_column('city', sa.Column('level', sa.INTEGER(), nullable=False))
    op.drop_column('city', 'gugun')
    op.drop_column('city', 'sido')
    # ### end Alembic commands ###
